account/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/',views.user_register,name='user_register'),
    path('login/',views.user_login,name='user_login'),
    path('logout/',views.user_logout,name='user_logout'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('profile/',views.user_profile,name='user_profile'),
    path('msg/',views.msg,name='msg'),
    path('favorite/',views.user_favorite,name='user_favorite'),
]

account/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile_user')
    phone = models.IntegerField(null=True)
    first_name = models.CharField(max_length=100, null=True)
    last_name = models.CharField(max_length=100, null=True)
    country = models.CharField(max_length=100, null=True)
    city = models.CharField(max_length=100, null=True)
    address = models.CharField(max_length=100, null=True)
    image = models.ImageField(upload_to='media/owner_profile/', default='media/default_images/avatar.png')

    def __str__(self):
        return self.user.username

    @property
    def complete(self):
        if self.phone is not None and self.first_name is not None and self.last_name is not None and self.country and self.city is not None and self.address is not None:
            return True
        else:
            return False


def save_profile_user(sender, **kwargs):
    if kwargs['created']:
        profile_user = Profile(user=kwargs['instance'])
        profile_user.save()


post_save.connect(save_profile_user, sender=User)


class Messages(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    text = models.TextField()

    def __str__(self):
        return self.user.username

account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *


class UserRegisterForm(forms.Form):
    user_name = forms.CharField(max_length=100, )
    email = forms.EmailField()
    password = forms.CharField(max_length=20)

    def clean_user_name(self):
        user = self.cleaned_data['user_name']
        if User.objects.filter(username=user).exists():
            raise forms.ValidationError('User Exists')
        return user

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('email already exist')
        return email


class UserLoginForm(forms.Form):
    user = forms.CharField()
    password = forms.CharField()


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('phone', 'first_name', 'last_name', 'country', 'city', 'address', 'image',)

account/views.py
from django.shortcuts import render, redirect
from .forms import *
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .models import *
from django.contrib.auth.decorators import login_required
from skills.models import *
from skills.forms import SkillFrom
from request.models import Request


def user_register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = User.objects.create_user(username=data['user_name'], email=data['email'], password=data['password'])
            user.active = True
            user.save()
            login(request, user)
            messages.success(request, 'welcome')
            return redirect('accounts:dashboard')
        else:
            messages.error(request, 'enter valid data')
    else:
        form = UserRegisterForm()
    context = {'form': form}
    return render(request, 'accounts/register.html', context)


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            try:
                user = authenticate(request, username=User.objects.get(email=data['user']), password=data['password'])
            except:
                user = authenticate(request, username=data['user'], password=data['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'you loged in')
                return redirect('accounts:dashboard')
            else:
                messages.warning(request, 'wrong information')
    else:
        form = UserLoginForm()
    return render(request, 'accounts/register.html')


def user_logout(request):
    logout(request)
    messages.success(request, 'you have loged out')
    return redirect('home:main')


@login_required(login_url='accounts:user_register')
def dashboard(reuqest):
    user = User.objects.get(id=reuqest.user.id)
    all_category = SkillsCategory.objects.all()
    all_times = SkillsTime.objects.all()
    user_skills = Skills.objects.filter(user=reuqest.user).order_by('-create')
    form = SkillFrom()
    send_request = Request.objects.filter(user=reuqest.user, status='pending')
    context = {'user': user, 'all_category': all_category, 'all_times': all_times, 'user_skills': user_skills,
               'form': form, 'send_request': send_request}
    return render(reuqest, 'accounts/dashboard.html', context)


@login_required(login_url='accounts:user_register')
def user_profile(request):
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile_user)
        if profile_form.is_valid() and request.user.profile_user.complete:
            profile_form.save()
            messages.success(request, 'updated')
        elif profile_form.is_valid() and not request.user.profile_user.complete:
            messages.error(request, 'please complete your account first')
        else:
            messages.error(request, 'enter valid data')
            print(profile_form.errors)
    else:
        profile_form = ProfileForm(instance=request.user.profile_user)
    context = {'profile_form': profile_form}
    return render(request, 'accounts/profile.html', context)


@login_required(login_url='accounts:user_register')
def msg(request):
    all_msg = Messages.objects.filter(user=request.user).order_by('-date')
    context = {'msg': all_msg}
    return render(request, 'accounts/messages.html', context)


@login_required(login_url='accounts:user_register')
def user_favorite(request):
    skills = request.user.skills_like.all()
    context = {'skills': skills}
    return render(request, 'accounts/favorite.html', context)

account/templates/accounts/dashboard.html
{% extends '_base.html' %}
{% load static %}
{% block title %}dashboard{% endblock %}
{% block body %}
    <div style="width: 100vw;height: 90vh;" class="d-flex align-items-center">
        <div style="width: 20%;height: 95%;border: 1px dashed skyblue" class="mx-4 shadow rounded">
            <div style="width: 100%;height:30%" class="d-flex align-items-center justify-content-center">
                <div style="width: 150px;height: 150px;background-image: url({{ user.profile_user.image.url }});background-size: cover;background-position: center"
                     class="rounded-circle border"></div>
            </div>
            <p class="text-center mt-4">{{ user.username }}</p>
            <p class="text-center">{{ user.email }}</p>
            <div style="width: 100%;height:30%"
                 class="d-flex align-items-center justify-content-center flex-column px-4">
                <a href="{% url 'accounts:user_profile' %}" class="btn btn-outline-primary">
                    {% if request.user.profile_user.complete %}Edit{% else %}Complete{% endif %} Account</a>
                {% if request.user.profile_user.complete %}
                    <a href="{% url 'user:user_profile' user.username %}" class="btn btn-outline-dark mt-2">Public
                        profile</a>
                    <div class="alert alert-success mt-4" role="alert">
                        Account is complete
                    </div>
                {% else %}
                    <div class="alert alert-danger mt-4" role="alert">
                        Account isn't complete
                    </div>
                {% endif %}
            </div>
            <div style="width: 100%" class="d-flex justify-content-center flex-column align-items-center">
                <a href="{% url 'accounts:user_favorite' %}" class="btn btn-outline-warning mt-2">Favorites</a>
                <a href="{% url 'accounts:user_logout' %}" class="btn btn-outline-danger mt-2">Logout</a>
            </div>
        </div>
        <div style="width: 25%;height: 95%;border: 1px dashed skyblue;overflow: scroll"
             class="mx-4 shadow rounded text-center px-3">
            {% if request.user.profile_user.complete %}
                <h5 class="my-3">Your Skills</h5>
                <button type="button" class="btn btn-outline-primary mb-3"><i class="bi bi-plus" data-bs-toggle="modal"
                                                                              data-bs-target="#exampleModal"></i>
                </button>
                {% if user_skills %}
                    {% for s in user_skills %}
                        <a href="{% url 'skills:skill_info' s.id %}" style="text-decoration: none;">
                            <div class="alert alert-info text-dark" role="alert">
                                {{ s.title }}<a href="{% url 'skills:skill_delete' s.id %}"><i
                                    class="bi bi-trash ms-2 text-danger"></i></a>
                            </div>
                        </a>
                    {% endfor %}
                {% else %}
                    <h6 style="margin-top: 80px">You dont have any skill yet !</h6>
                {% endif %}
            {% else %}
                <h5 class="my-3">Your Skills</h5>
                <div class="alert alert-warning" role="alert">
                    Please complete your account for add skill
                </div>
            {% endif %}
        </div>
        <div style="width: 45%;height: 95%;border: 1px dashed skyblue" class="mx-4 shadow rounded text-center px-4">
            <h5 class="my-3">Your Pending Requests</h5>
            {% for s in send_request %}
                <div class="alert alert-secondary row" role="alert">
                    <div class="col-4"><a href="{% url 'skills:skill_info' s.skill.id %}" style="text-decoration: none"
                                          class="text-dark">{{ s.skill.title }}</a></div>
                    <div class="col-3"><a href="{% url 'user:user_profile' s.skill.user.username %}"
                                          style="text-decoration: none"
                                          class="text-dark">{{ s.skill.user.profile_user.first_name }} {{ s.skill.user.profile_user.last_name }}</a>
                    </div>
                    <div class="col-2">pending</div>
                    <div class="col-3">{{ s.create.date }}</div>
                </div>
            {% endfor %}
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <form class="modal-dialog" method="post" action="{% url 'skills:skills_add' %}">
            {% csrf_token %}
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Skill</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form class="form-floating">
                        <input name="title" type="text" class="form-control" id="floatingInputValue">
                        <label for="floatingInputValue">Title</label>
                    </form>
                    <select name="category" class="form-select my-4" aria-label="Default select example">
                        {% for c in all_category %}
                            <option value="{{ c.id }}">{{ c.name }}</option>
                        {% endfor %}
                    </select>
                    <select name="time" class="form-select my-4" aria-label="Default select example">
                        {% for t in all_times %}
                            <option value="{{ t.id }}">{{ t.time }}</option>
                        {% endfor %}
                    </select>
                    <div class="form-floating">
                        <textarea name="description" class="form-control" placeholder="Leave a comment here"
                                  id="floatingTextarea"></textarea>
                        <label for="floatingTextarea">Description</label>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

account/templates/accounts/favorite.html
{% extends '_base.html' %}
{% block title %}messages{% endblock %}
{% block body %}
    <h4 class="text-center my-3">Your Favorites</h4>
    <div style="width: 100vw;height: 75vh;" class="d-flex justify-content-center">
        <div style="width: 60%;height: 100%;overflow-y: scroll" class="shadow border border-primary rounded p-4">
            {% if skills %}
                {% for s in skills %}
                    <div class="alert alert-warning row" role="alert">
                        <div class="col-10"><a style="text-decoration: none" class="text-dark"
                                               href="{% url 'skills:skill_info' s.id %}">{{ s.title }}</a></div>
                        <div class="col-2"><a style="text-decoration: none" class="text-danger"
                                               href="{% url 'skills:skill_favorite' s.id %}"><i class="bi bi-trash-fill"></i></a></div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="alert alert-warning row" role="alert">
                    <div class="col-10">you dont have any favorite !</div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

account/templates/accounts/messages.html
{% extends '_base.html' %}
{% block title %}messages{% endblock %}
{% block body %}
    <h4 class="text-center my-3">Your messages</h4>
    <div style="width: 100vw;height: 75vh;" class="d-flex justify-content-center">
        <div style="width: 60%;height: 100%;overflow-y: scroll" class="shadow border border-primary rounded p-4">
            {% if msg %}
                {% for m in msg %}
                    <div class="alert alert-warning row" role="alert">
                        <div class="col-10">{{ m.text }}</div>
                        <div class="col-2">{{ m.date.date }}</div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="alert alert-warning row" role="alert">
                    <div class="col-10">you dont have any message !</div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

account/templates/accounts/profile.html
{% extends '_base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'accounts/css/profile.css' %}">{% endblock %}
{% block title %}profle{% endblock %}
{% block body %}
    <div class="row d-flex justify-content-center">
        <div class="d-flex justify-content-center">
            <div class="rounded-circle mt-3" style="width: 150px;height: 150px;z-index: 1000;
                    overflow: hidden;background-image: url({{ request.user.profile_user.image.url }}); background-size: cover;background-position: center">
            </div>
            <label for="file-upload" class="custom-file-upload">
                <i class="bi bi-pencil-fill rounded border shadow"></i>
            </label>
        </div>
        <div class="user_information shadow bg-white mt-0 rounded" style="width: 92%;transform: translateY(-40px)">
            <form enctype="multipart/form-data" class="row my-3 mt-5" method="post"
                  action="{% url 'accounts:user_profile' %}">
                {% csrf_token %}
                <input name="image" id="file-upload" type="file" oninput="this.form.submit()" accept="image/*"/>
                <div class="col-6">
                    <div class="form-floating mb-3">
                        <input type="text" class="disabled form-control" id="floatingInput"
                               placeholder="name@example.com"
                               disabled>
                        <label for="floatingInput">{{ request.user.username }}</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="floatingInput" placeholder="name@example.com"
                               name="first_name"
                               {% if request.user.profile_user.first_name %}value="{{ request.user.profile_user.first_name }}"{% endif %}>
                        <label for="floatingInput">First name</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="number" class="form-control" id="floatingInput" minlength="11"
                               placeholder="name@example.com" name="phone"
                               {% if request.user.profile_user.phone %}value="{{ request.user.profile_user.phone }}"{% endif %}>
                        <label for="floatingInput">Phone number</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="floatingInput"
                               name="country" placeholder="name@example.com"
                               {% if request.user.profile_user.country %}value="{{ request.user.profile_user.country }}"{% endif %}>
                        <label for="floatingInput">Country</label>
                    </div>
                    <button type="submit" class="btn btn-outline-primary mt-3 me-2">save</button>
                    <a href="{% url 'accounts:dashboard' %}" class="btn btn-outline-danger mt-3">back</a>
                </div>
                <div class="col-6">
                    <div class="form-floating mb-3">
                        <input type="text" class="disabled form-control" id="floatingInput"
                               placeholder="name@example.com"
                               disabled>
                        <label for="floatingInput">{{ request.user.email }}</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="floatingInput" placeholder="name@example.com"
                               name="last_name"
                               {% if request.user.profile_user.last_name %}value="{{ request.user.profile_user.last_name }}" {% endif %}>
                        <label for="floatingInput">Last name</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="floatingInput" placeholder="name@example.com"
                               name="city" {% if request.user.profile_user.city %}
                               value="{{ request.user.profile_user.city }}"{% endif %}>
                        <label for="floatingInput">City</label>
                    </div>
                    <div class="form-floating">
                        <textarea class="form-control" placeholder="Leave a comment here"
                                  id="floatingTextarea" name="address">{% if request.user.profile_user.address %}{{ request.user.profile_user.address }}{% endif %}</textarea>
                        <label for="floatingTextarea">Address</label>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

account/templates/accounts/register.html
{% extends '_accounts.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'accounts/css/register.css' %}">{% endblock %}
{% block title %}register{% endblock %}
{% block body %}
    <div class="container" id="container">
        <div class="form-container sign-up-container">
            <form method="post" action="{% url 'accounts:user_register' %}">
                {% csrf_token %}
                <h1>Create Account</h1>
                <div class="social-container">
                    <a href="#" class="social"><i class="bi bi-facebook"></i></a>
                    <a href="#" class="social"><i class="bi bi-google"></i></a>
                    <a href="#" class="social"><i class="bi bi-github"></i></a>
                </div>
                <span>or use your email for registration</span>
                <input name="user_name" type="text" placeholder="Username"/>
                <input name="email" type="email" placeholder="Email"/>
                <input name="password" type="password" placeholder="Password"/>
                <button type="submit">Sign Up</button>
            </form>
        </div>
        <div class="form-container sign-in-container">
            <form method="post" action="{% url 'accounts:user_login' %}">
                {% csrf_token %}
                <h1>Sign in</h1>
                <div class="social-container">
                    <a href="#" class="social"><i class="bi bi-facebook"></i></a>
                    <a href="#" class="social"><i class="bi bi-google"></i></a>
                    <a href="#" class="social"><i class="bi bi-github"></i></a>
                </div>
                <span>or use your account</span>
                <input name="user" type="text" placeholder="Email or Username"/>
                <input name="password" type="password" placeholder="Password"/>
                <a href="#">Forgot your password?</a>
                <button type="submit">Sign In</button>
            </form>
        </div>
        <div class="overlay-container">
            <div class="overlay">
                <div class="overlay-panel overlay-left">
                    <h1>Welcome Back!</h1>
                    <p>To keep connected with us please login with your personal info</p>
                    <button class="ghost" id="signIn">Sign In</button>
                </div>
                <div class="overlay-panel overlay-right">
                    <h1>Hello, Friend!</h1>
                    <p>Enter your personal details and start journey with us</p>
                    <button class="ghost" id="signUp">Sign Up</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script rel="stylesheet" src="{% static 'accounts/js/register.js' %}"></script>{% endblock %}