skills/urls.py
from django.urls import path
from . import views

app_name = 'skills'

urlpatterns = [
    path('add/', views.skills_add, name='skills_add'),
    path('delete/<int:id>/', views.skill_delete, name='skill_delete'),
    path('<int:id>/', views.skill_info, name='skill_info'),
    path('explore/', views.explore, name='explore'),
    path('explore/<slug>/', views.explore, name='user_explore'),
    path('search/', views.skill_search, name='skill_search'),
    path('favorite/<int:id>/',views.skill_favorite,name='skill_favorite'),
    path('rate/<int:id>/',views.skill_rate,name='skill_rate'),
]

skills/models.py
from django.db import models
from django.contrib.auth.models import User


class Skills(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey('SkillsCategory', on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    time = models.ForeignKey('SkillsTime', on_delete=models.CASCADE)
    description = models.TextField()
    create = models.DateTimeField(auto_now_add=True, null=True)
    like = models.ManyToManyField(User, related_name='skills_like',null=True,blank=True)
    rating = models.ManyToManyField('Rate',related_name='skills_rating',null=True,blank=True)

    def __str__(self):
        return self.title


class SkillsCategory(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class SkillsTime(models.Model):
    time = models.CharField(max_length=100)

    def __str__(self):
        return self.time


class Rate(models.Model):
    rate = models.PositiveIntegerField()

    def __str__(self):
        return f'rate is {str(self.rate)}'

skills/forms.py
from django import forms
from .models import *


class SkillFrom(forms.ModelForm):
    class Meta:
        model = Skills
        fields = ('category', 'title', 'time', 'description',)


class SearchForm(forms.Form):
    search = forms.CharField(max_length=20)


class SkillRateForm(forms.ModelForm):
    class Meta:
        model = Rate
        fields = ('rate',)

skills/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import *
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q, Min, Max
import datetime
from request.models import Request
from django.db.models import Avg


@login_required(login_url='accounts:user_register')
def skills_add(request):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        form = SkillFrom(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            skill = Skills.objects.create(user=request.user, category=data['category'], title=data['title'],
                                          time=data['time'], description=data['description'])
            skill.save()
            messages.success(request, 'skill add')
        else:
            messages.error(request, 'enter valid data')
            print(form.errors)
    return redirect(url)


@login_required(login_url='accounts:user_register')
def skill_delete(request, id):
    skill = get_object_or_404(Skills, id=id)
    if skill.user == request.user:
        skill.delete()
        messages.success(request, 'deleted')
    return redirect('accounts:dashboard')


def skill_info(request, id):
    skill = get_object_or_404(Skills, id=id)
    avg = skill.rating.all().aggregate(Avg('rate'))
    info = skill.like.all()
    d1 = datetime.date.today()
    d2 = d1.month + 1
    if d2 < 10:
        d3 = f'0{d2}'
    else:
        d3 = d2
    context = {'skill': skill, 'next_month': d3, 'info': info,'avg':avg['rate__avg']}
    return render(request, 'skills/info.html', context)


def explore(request, slug=None):
    if slug:
        user = get_object_or_404(User, username=slug)
        if user.profile_user.complete:
            skills = Skills.objects.filter(user=user).order_by('-create')
        else:
            return redirect('home:main')
    else:
        skills = Skills.objects.all().order_by('-create')
    form = SearchForm()
    paginator = Paginator(skills, 12)
    page_num = request.GET.get('page')
    page_obj = paginator.get_page(page_num)
    contex = {'skills': page_obj, 'form': form}
    return render(request, 'skills/explore.html', contex)


def skill_search(request):
    skills = Skills.objects.all()
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data['search']
            skills = skills.filter(Q(title__contains=data))
            paginator = Paginator(skills, 12)
            page_num = request.GET.get('page')
            page_obj = paginator.get_page(page_num)
    return render(request, 'skills/explore.html', {'form': form, 'skills': page_obj})


@login_required(login_url='accounts:user_register')
def skill_favorite(request, id):
    skill = get_object_or_404(Skills, id=id)
    if request.user == skill.user:
        return redirect('home:main')
    if request.user in skill.like.all():
        skill.like.remove(request.user)
        skill.save()
    else:
        skill.like.add(request.user)
        skill.save()
    return redirect(request.META.get('HTTP_REFERER'))


@login_required(login_url='accounts:user_register')
def skill_rate(request,id):
    rq = Request.objects.filter(id=id,user=request.user)
    if not rq.exists():
        return redirect('home:main')
    rq = Request.objects.get(id=id)
    skill = rq.skill
    if request.method == 'POST':
        form = SkillRateForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data['rate']
            rate = Rate.objects.create(rate=data)
            skill.rating.add(rate)
            skill.save()
            rq.delete()
            messages.success(request,'rated !')
        else:
            messages.error(request,'enter valid data')
    return redirect('request:all_request')

skills/templates/skills/explore.html
{% extends '_base.html' %}
{% block title %}explore{% endblock %}
{% block body %}
    <div style="width: 100vw" class="d-flex justify-content-center mt-4 mb-2">
        <form method="post" action="{% url 'skills:skill_search' %}" class="d-flex" role="search">
            {% csrf_token %}
            <input name="search" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
    </div>
    <div class="row d-flex justify-content-center" style="width: 100vw">
        {% for s in skills %}
            <div style="width: 20vw;height: 80vh"
                 class="m-4 rounded col-3 d-flex flex-column align-items-center border border-primary">
                <div style="width: 100%;" class="d-flex justify-content-center my-3">
                    <a href="{% url 'user:user_profile' s.user.username %}">
                        <div style="width: 100px;height: 100px;background-image: url({{ s.user.profile_user.image.url }});background-size: cover;background-position: center"
                             class="border rounded-circle"></div>
                    </a>
                </div>
                <div style="width: 100%;" class="d-flex flex-column align-items-center my-3">
                    <h5>{{ s.title }}</h5>
                    <p>{{ s.user.profile_user.country }},{{ s.user.profile_user.city }}</p>
                    <p><i class="bi bi-alarm me-1"></i>{{ s.time }}</p>
                    <div style="width: 85%;height: 27vh;overflow: hidden" class="">{{ s.description }}</div>
                    <a href="{% url 'skills:skill_info' s.id %}" class="btn btn-outline-primary mt-3">Show more</a>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="d-flex justify-content-center" aria-label="...">
        <ul class="pagination">
            <li class="page-item">
                <a class="page-link {% if not skills.has_previous %}disabled{% endif %}"
                   href="{% if skills.has_previous %}?page={{ skills.previous_page_number }}{% endif %}">Prev</a>
            </li>
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ skills.number }}">{{ skills.number }}</a>
            </li>
            <li class="page-item">
                <a class="page-link {% if not skills.has_next %}disabled{% endif %}"
                   href="{% if skills.has_next %}?page={{ skills.next_page_number }}{% endif %}">Next</a>
            </li>
        </ul>
    </div>
{% endblock %}

skills/templates/skills/info.html
{% extends '_base.html' %}
{% block title %}skill hub | {{ skill.id }}{% endblock %}
{% block body %}
    <div data-width="100vh" class="d-flex flex-column align-items-center">
        <div style="width: 50%" class="shadow border rounded mt-4 d-flex flex-column align-items-center">
            <h4 class="my-3"><a href=""></a>{{ skill.title }}</h4>
            <p>By:<img class="rounded-circle border ms-3 me-1" src="{{ skill.user.profile_user.image.url }}"
                       style="width: 30px;height: 30px"><a href="{% url 'user:user_profile' skill.user.username %}"
                                                           class="text-dark"
                                                           style="text-decoration: none">{{ skill.user.profile_user.first_name }} {{ skill.user.profile_user.last_name }}</a>
            </p>
            <p>{{ skill.category }} | {{ skill.user.profile_user.city }},{{ skill.user.profile_user.country }}</p>
            <p>{% if avg %}
                {{ avg }}
            {% else %}
                There are no rate yet !
            {% endif %}</p>
            <p>{{ skill.time }}</p>
            <div style="width: 80%;border: 1px dashed skyblue" class="rounded mb-4 p-4">{{ skill.description }}</div>
            {% if request.user.is_authenticated %}
                {% if skill.user !=  request.user %}
                    <p><a href="{% url 'skills:skill_favorite' skill.id %}" class="mb-3"><i
                            class="bi bi-star{% if request.user in info %}-fill{% endif %} text-warning"></i></a></p>
                    <form method="post" action="{% url 'request:request_add' skill.id %}" class="d-flex flex-column">
                        {% csrf_token %}
                        <input type="time" name="time" required>
                        <input required class="my-2" type="date" id="datemax" name="date"
                               min="20{% now 'y' %}-{% now 'm' %}-{% now 'd' %}"
                               max="20{% now 'y' %}-{{ next_month }}-{% now 'd' %}"><br><br>
                        <button type="submit" class="btn btn-outline-dark mb-4">Request</button>
                    </form>
                {% else %}
                    <a href="{% url 'skills:skill_delete' skill.id %}" class="btn btn-outline-dark mb-4"><i
                            class="bi bi-trash"></i></a>
                {% endif %}
            {% else %}
                <a href="{% url 'accounts:user_register' %}" class="btn btn-outline-dark mb-4">Login</a>
            {% endif %}
        </div>
    </div>
{% endblock %}