account/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/',views.user_register,name='user_register'),
    path('login/',views.user_login,name='user_login'),
    path('logout/',views.user_logout,name='user_logout'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('profile/',views.user_profile,name='user_profile'),
    path('msg/',views.msg,name='msg'),
    path('favorite/',views.user_favorite,name='user_favorite'),
]

djangoProject/project/project/urls.py
from django.urls import include, path
from app import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('community/', views.community, name='community'),
    path('community/<int:content_id>/', views.content, name='content'),
    path('create/', views.create, name='create'),
    path('login/github/', include('social_django.urls', namespace='social')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
DEBUG = True

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('',views.main,name='main'),
    path('contact/',views.contact_add,name='contact_add')
]

request/urls.py
from django.urls import path
from . import views

app_name = 'request'

urlpatterns = [
    path('',views.all_request,name='all_request'),
    path('add/<int:id>/',views.request_add,name='request_add'),
    path('<int:id>/',views.request_details,name='request_details'),
    path('accept/<int:id>/',views.request_accept,name='request_accept'),
    path('reject/<int:id>/',views.request_reject,name='reject'),
]

skill_hub/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('account.urls',namespace='accounts')),
    path('',include('home.urls',namespace='urls')),
    path('skills/',include('skills.urls',namespace='skills')),
    path('user/',include('user.urls',namespace='user')),
    path('request/',include('request.urls',namespace='request'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skills/urls.py
from django.urls import path
from . import views

app_name = 'skills'

urlpatterns = [
    path('add/', views.skills_add, name='skills_add'),
    path('delete/<int:id>/', views.skill_delete, name='skill_delete'),
    path('<int:id>/', views.skill_info, name='skill_info'),
    path('explore/', views.explore, name='explore'),
    path('explore/<slug>/', views.explore, name='user_explore'),
    path('search/', views.skill_search, name='skill_search'),
    path('favorite/<int:id>/',views.skill_favorite,name='skill_favorite'),
    path('rate/<int:id>/',views.skill_rate,name='skill_rate'),
]

urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


admin.site.site_header = "Login to Skill Hub";
admin.site.site_title =  " Welcome to Skill's Hub Dashboard";
admin.site.site_index =  " Welcome to the Portal ";


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('account.urls',namespace='accounts')),
    path('',include('home.urls',namespace='urls')),
    path('blog/', include('blog.urls', namespace='blog')),  # Include the blog app URLs with a namespace
    path('skills/',include('skills.urls',namespace='skills')),
    path('user/',include('user.urls',namespace='user')),
    path('request/',include('request.urls',namespace='request')),
    path('auth/', include('social_django.urls', namespace='social')),#For Social Django Authentication
    path('', include('admin_material.urls')),# Admin panel
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile_user')
    phone = models.IntegerField(null=True)
    first_name = models.CharField(max_length=100, null=True)
    last_name = models.CharField(max_length=100, null=True)
    country = models.CharField(max_length=100, null=True)
    city = models.CharField(max_length=100, null=True)
    address = models.CharField(max_length=100, null=True)
    image = models.ImageField(upload_to='media/owner_profile/', default='media/default_images/avatar.png')

    def __str__(self):
        return self.user.username

    @property
    def complete(self):
        if self.phone is not None and self.first_name is not None and self.last_name is not None and self.country and self.city is not None and self.address is not None:
            return True
        else:
            return False


def save_profile_user(sender, **kwargs):
    if kwargs['created']:
        profile_user = Profile(user=kwargs['instance'])
        profile_user.save()


post_save.connect(save_profile_user, sender=User)


class Messages(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    text = models.TextField()

    def __str__(self):
        return self.user.username

account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *


class UserRegisterForm(forms.Form):
    user_name = forms.CharField(max_length=100, )
    email = forms.EmailField()
    password = forms.CharField(max_length=20)

    def clean_user_name(self):
        user = self.cleaned_data['user_name']
        if User.objects.filter(username=user).exists():
            raise forms.ValidationError('User Exists')
        return user

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('email already exist')
        return email


class UserLoginForm(forms.Form):
    user = forms.CharField()
    password = forms.CharField()


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('phone', 'first_name', 'last_name', 'country', 'city', 'address', 'image',)

account/views.py
from django.shortcuts import render, redirect
from .forms import *
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .models import *
from django.contrib.auth.decorators import login_required
from skills.models import *
from skills.forms import SkillFrom
from request.models import Request


def user_register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = User.objects.create_user(username=data['user_name'], email=data['email'], password=data['password'])
            user.active = True
            user.save()
            login(request, user)
            messages.success(request, 'welcome')
            return redirect('accounts:dashboard')
        else:
            messages.error(request, 'enter valid data')
    else:
        form = UserRegisterForm()
    context = {'form': form}
    return render(request, 'accounts/register.html', context)


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            try:
                user = authenticate(request, username=User.objects.get(email=data['user']), password=data['password'])
            except:
                user = authenticate(request, username=data['user'], password=data['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'you loged in')
                return redirect('accounts:dashboard')
            else:
                messages.warning(request, 'wrong information')
    else:
        form = UserLoginForm()
    return render(request, 'accounts/register.html')


def user_logout(request):
    logout(request)
    messages.success(request, 'you have loged out')
    return redirect('home:main')


@login_required(login_url='accounts:user_register')
def dashboard(reuqest):
    user = User.objects.get(id=reuqest.user.id)
    all_category = SkillsCategory.objects.all()
    all_times = SkillsTime.objects.all()
    user_skills = Skills.objects.filter(user=reuqest.user).order_by('-create')
    form = SkillFrom()
    send_request = Request.objects.filter(user=reuqest.user, status='pending')
    context = {'user': user, 'all_category': all_category, 'all_times': all_times, 'user_skills': user_skills,
               'form': form, 'send_request': send_request}
    return render(reuqest, 'accounts/dashboard.html', context)


@login_required(login_url='accounts:user_register')
def user_profile(request):
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile_user)
        if profile_form.is_valid() and request.user.profile_user.complete:
            profile_form.save()
            messages.success(request, 'updated')
        elif profile_form.is_valid() and not request.user.profile_user.complete:
            messages.error(request, 'please complete your account first')
        else:
            messages.error(request, 'enter valid data')
            print(profile_form.errors)
    else:
        profile_form = ProfileForm(instance=request.user.profile_user)
    context = {'profile_form': profile_form}
    return render(request, 'accounts/profile.html', context)


@login_required(login_url='accounts:user_register')
def msg(request):
    all_msg = Messages.objects.filter(user=request.user).order_by('-date')
    context = {'msg': all_msg}
    return render(request, 'accounts/messages.html', context)


@login_required(login_url='accounts:user_register')
def user_favorite(request):
    skills = request.user.skills_like.all()
    context = {'skills': skills}
    return render(request, 'accounts/favorite.html', context)

templates/_accounts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
    {% block css %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block body %}{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.min.js"
        integrity="sha512-pumBsjNRGGqkPzKHndZMaAG+bir374sORyzM3uulLV14lN5LyykqNk8eEeUlUkB3U0M4FApyaHraT65ihJhDpQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
{% include 'messages.html' %}
{% block js %}{% endblock %}
</body>
</html>

templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
    {% block css %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home:main' %}">Skill Hub</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home:main' %}"><i
                            class="bi bi-house me-1"></i>Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'skills:explore' %}"><i
                            class="bi bi-compass me-1"></i>Explore</a>
                </li>
                
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'accounts:dashboard' %}"><i
                                class="bi bi-person me-1"></i>Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'request:all_request' %}"><i
                                class="bi bi-check2-circle me-1"></i>Requests</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'accounts:msg' %}"><i
                                class="bi bi-chat-left-text me-1"></i>Messages</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'accounts:user_register' %}"><i
                                class="bi bi-person me-1"></i>Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'accounts:user_logout' %}"><i class="bi bi-box-arrow-right me-1"></i></a>
                    </li>

            </ul>
        </div>
    </div>
</nav>
{% block body %}{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.min.js"
        integrity="sha512-pumBsjNRGGqkPzKHndZMaAG+bir374sORyzM3uulLV14lN5LyykqNk8eEeUlUkB3U0M4FApyaHraT65ihJhDpQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
{% include 'messages.html' %}
{% block js %}{% endblock %}
</body>
</html>

templates/messages.html
<script>
    function messages(msg, tags) {
        if (tags === 'error') {
            color = 'linear-gradient(to right, #ed213a, #d82816)'
        } else if (tags === 'warning') {
            color = "linear-gradient(to left, #cac531, #e2ec65)"
        } else {
            color = "linear-gradient(to left, #5C83F7, #6E9DFD)"
        }
        Toastify({
            text: msg,
            duration: 9000,
            newWindow: true,
            gravity: "top",
            close: true,
            position: "right",
            stopOnFocus: true,
            style: {
                background: color,
                direction: 'ltr',
                borderRadius: '6px',
            },
        }).showToast();
    }
    {% if messages %}
        {% for msg in messages %}
            const msg = "{{msg}}";
            {% if msg.tags %}const tags = "{{ msg.tags }}"{% endif %}
            messages(msg, tags)
        {% endfor %}
    {% endif %}
    toast_btn = document.getElementsByClassName('toast-close')
    for (let i = 0; i < toast_btn.length; ++i) {
        let item = toast_btn[i];
        item.innerHTML = '<i class="bi bi-x"></i>'
    }
</script>