request/urls.py
from django.urls import path
from . import views

app_name = 'request'

urlpatterns = [
    path('',views.all_request,name='all_request'),
    path('add/<int:id>/',views.request_add,name='request_add'),
    path('<int:id>/',views.request_details,name='request_details'),
    path('accept/<int:id>/',views.request_accept,name='request_accept'),
    path('reject/<int:id>/',views.request_reject,name='reject'),
]

request/models.py
from django.db import models
from skills.models import Skills
from django.contrib.auth.models import User


class Request(models.Model):
    skill = models.ForeignKey(Skills, on_delete=models.CASCADE, related_name='request_skill')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='request_user')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='request_receiver')
    REQUEST_CHOICES = (
        ('accepted', 'accepted'),
        ('pending', 'pending'),
    )
    status = models.CharField(choices=REQUEST_CHOICES, max_length=100)
    date = models.DateField()
    time = models.TimeField()
    create = models.DateTimeField(auto_now_add=True,null=True)

    def __str__(self):
        return self.skill.title

class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_messages')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='received_messages')
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Message from {self.sender.username} to {self.receiver.username} at {self.timestamp}"

request/forms.py
from django import forms
from .models import *


class RequestForm(forms.ModelForm):
    class Meta:
        model = Request
        fields = ('date', 'time',)


request/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from account.models import Messages
from django.db.models import Q
import datetime

@login_required(login_url='accounts:user_register')
def request_add(request, id):
    skill = get_object_or_404(Skills, id=id)
    if request.method == 'POST':
        form = RequestForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            if Request.objects.filter(receiver=skill.user, date=data['date'], time=data['time']):
                messages.warning(request, 'user Time is full')
                return redirect(request.META.get('HTTP_REFERER'))
            else:
                Request.objects.create(skill=skill, user=request.user, receiver=skill.user, status='pending',
                                       date=data['date'], time=data['time'])
                messages.success(request, 'request added')
        else:
            messages.error(request, 'enter valid date')
    return redirect('accounts:dashboard')


@login_required(login_url='accounts:user_register')
def all_request(request):
    requests = Request.objects.filter(receiver=request.user).order_by('-create')
    requests = Request.objects.filter(Q(receiver=request.user) | Q(user=request.user) & Q(status='accepted')).order_by(
        '-create')
    context = {'requests': requests}
    return render(request, 'request/request.html', context)


@login_required(login_url='accounts:user_register')
def request_details(request, id):
    rq = get_object_or_404(Request, id=id)
    if rq.receiver != request.user:
        redirect('home:main')
    if rq.date > datetime.date.today():
        status = 'before'
    elif rq.date < datetime.date.today() :
        status = 'after'
    else:
        status = 'during'
    requests = Request.objects.filter(Q(receiver=request.user) | Q(user=request.user) & Q(status='accepted')).order_by(
        '-create')
    context = {'requests': requests, 'rq': rq,'status':status}
    return render(request, 'request/details.html', context)


@login_required(login_url='accounts:user_register')
def request_accept(request, id):
    rq = get_object_or_404(Request, id=id)
    if rq.receiver != request.user:
        redirect('home:main')
    rq.status = 'accepted'
    rq.save()
    messages.success(request, 'request accepted')
    return redirect(request.META.get('HTTP_REFERER'))


@login_required(login_url='accounts:user_register')
def request_reject(request, id):
    rq = get_object_or_404(Request, id=id)
    if rq.receiver == request.user or rq.user == request.user and rq.status == 'accepted':
        rq.delete()
        messages.success(request, 'request deleted')
        Messages.objects.create(user=rq.user, text=f'your request for skill {rq.skill.id} rejected / deleted')
        Messages.objects.create(user=rq.receiver, text=f'the request for your skill {rq.skill.id} canceled / deleted')
        return redirect('request:all_request')
    else:
        redirect('home:main')

request/templates/request/details.html
{% extends '_base.html' %}
{% block title %}messages{% endblock %}
{% block body %}
    <div style="width: 100vw;height: 85vh;" class="d-flex justify-content-center mt-3">
        <div style="width: 93%;height: 100%;" class="shadow border border-primary rounded p-3 row">
            <div style="height: 100%;overflow-y: scroll;width: 36%" class="rounded border p-3">
                {% if requests %}
                    {% for r in requests %}
                        {% if r.status == 'pending' %}
                            <a href="{% url 'request:request_details' r.id %}"
                               class="btn btn-outline-dark form-control mb-3">{{ r.user.profile_user.first_name }} {{ r.user.profile_user.last_name }}
                                | {{ r.skill.title }}</a>
                        {% else %}
                            <a href="{% url 'request:request_details' r.id %}"
                               class="btn btn-success form-control mb-3">{{ r.user.profile_user.first_name }} {{ r.user.profile_user.last_name }}
                                | {{ r.skill.title }}</a>
                        {% endif %}
                    {% endfor %}
                {% else %}
                    <p class="text-center">you dont have any request yet !</p>
                {% endif %}
            </div>
            <div style="height: 100%;width: 3%"></div>
            <div style="height: 100%;overflow-y: scroll;width: 61%"
                 class="rounded border d-flex flex-column align-items-center">
                {% if rq.status == 'pending' %}
                    <div class="alert alert-primary row mt-3" role="alert" style="width: 100%">
                        <div class="col-2"><a href="{% url 'user:user_profile' rq.user.username %}"
                                              style="text-decoration: none;color: #052C65">{{ rq.user.profile_user.first_name }} {{ rq.user.profile_user.last_name }}</a>
                        </div>
                        <div class="col-4"><a href="{% url 'skills:skill_info' rq.skill.id %}"
                                              style="text-decoration: none;color: #052C65">{{ rq.skill.title }}</a>
                        </div>
                        <div class="col-4">
                            {{ rq.date }} | {{ rq.time }}
                        </div>
                        <div class="col-2">
                            <a href="{% url 'request:request_accept' rq.id %}"
                               class="btn btn-outline-success sm btn-sm"><i
                                    class="bi bi-check2-circle"></i></a>
                            <a href="{% url 'request:reject' rq.id %}" class="btn btn-outline-danger sm btn-sm"><i
                                    class="bi bi-x-circle"></i></a>
                        </div>
                    </div>
                {% else %}
                    <div style="width:80%;" class="border rounded mt-4 d-flex flex-column align-items-center">
                        <p class="my-2">from <a href="{% url 'user:user_profile' rq.user.username %}"
                                                style="text-decoration: none"
                                                class="text-dark">{{ rq.user.profile_user.first_name }} {{ rq.user.profile_user.last_name }}</a>
                            to <a href="{% url 'user:user_profile' rq.user.username %}" style="text-decoration: none"
                                  class="text-dark">{{ rq.receiver.profile_user.first_name }} {{ rq.receiver.profile_user.last_name }}</a>
                        </p>
                        <h5><a href="{% url 'skills:skill_info' rq.skill.id %}" style="text-decoration: none"
                               class="text-primary">{{ rq.skill.title }}</a></h5>
                        <p>{{ rq.skill.time }}
                            | {{ rq.receiver.profile_user.city }},{{ rq.receiver.profile_user.country }}</p>
                        <p>{{ rq.receiver.profile_user.phone }}</p>
                        <p>{{ rq.receiver.profile_user.address }}</p>
                        {% if status == 'before' %}
                            <div style="width: 60%" class="rounded border border-primary"><h5
                                    class="text-center p-3">{{ rq.date }} | {{ rq.time }}</h5></div>
                            <a href="{% url 'request:reject' rq.id %}" class="btn btn-outline-danger sm btn-sm my-3"><i
                                    class="bi bi-trash"></i></a>
                        {% elif status == 'after' %}
                            {% if rq.user == request.user %}
                                <p class="mb-3 text-warning">please rate skill</p>
                                <form method="post" action="{% url 'skills:skill_rate' rq.id %}"
                                      style="width: 60%" class="rounded border border-primary mb-3">
                                    {% csrf_token %}
                                    <select name="rate" class="form-select" aria-label="Default select example" oninput="this.form.submit()">
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                        <option value="4">4</option>
                                        <option value="5">5</option>
                                    </select>
                                </form>
                            {% else %}
                                <div style="width: 60%" class="rounded border border-primary mb-3"><h5
                                        class="text-center p-3">Your meet is over</h5></div>
                            {% endif %}
                        {% else %}
                            <div style="width: 60%" class="rounded border border-primary mb-3"><h5
                                    class="text-center p-3">Your meet is today !</h5></div>
                        {% endif %}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

request/templates/request/request.html
{% extends '_base.html' %}
{% block title %}messages{% endblock %}
{% block body %}
    <div style="width: 100vw;height: 85vh;" class="d-flex justify-content-center mt-3">
        <div style="width: 93%;height: 100%;" class="shadow border border-primary rounded p-3 row">
            <div style="height: 100%;overflow-y: scroll;width: 36%" class="rounded border p-3">
                {% if requests %}
                    {% for r in requests %}
                        {% if r.status == 'pending' %}
                            <a href="{% url 'request:request_details' r.id %}"
                               class="btn btn-outline-dark form-control mb-3">{{ r.user.profile_user.first_name }} {{ r.user.profile_user.last_name }}
                                | {{ r.skill.title }}</a>
                        {% else %}
                            <a href="{% url 'request:request_details' r.id %}"
                               class="btn btn-success form-control mb-3">{{ r.user.profile_user.first_name }} {{ r.user.profile_user.last_name }}
                                | {{ r.skill.title }}</a>
                        {% endif %}
                    {% endfor %}
                {% else %}
                    <p class="text-center">you dont have any request yet !</p>
                {% endif %}
            </div>
            <div style="height: 100%;width: 3%"></div>
            <div style="height: 100%;overflow-y: scroll;width: 61%"
                 class="rounded border d-flex flex-column align-items-center">
                <div class="alert alert-warning mt-4" role="alert">
                    You dont select any request yet !
                </div>
            </div>
        </div>
    </div>
{% endblock %}